@startuml

footer Page 3 of 3

title Spring Boot
[-> CompanyResource: GET /api/companies
CompanyResource -> CompanyService: List<CompanyDTO> findAll()
CompanyService -> CompanyRepository: List<CompanyDTO> findAll()
database "postgres"
CompanyRepository -> postgres: List<Company> findAll()
CompanyRepository -> postgres: JPA query
postgres -> CompanyRepository
CompanyRepository -> "CompanyMapper\n (Mapstruct)": convert List<Company>\n to List<CompanyDTO>
"CompanyMapper\n (Mapstruct)"-> CompanyService
CompanyService -> CompanyResource
CompanyResource ->[
@enduml
